### ISSUE TITLE
Running on DWY100K

### ISSUE THREAD

**Issue by DexterZeng** [thunlp/MuGNN#3]
Hi, thank you again for sharing the codes and earlier responses.

When running the code on DWY100K, it reported "RuntimeError: CUDA out of memory. Tried to allocate 1.77 GiB (GPU 0; 11.92 GiB total capacity; 10.43 GiB already allocated; 922.88 MiB free; 75.71 MiB cached)", which is understandable since the size of DWY100K is much larger than DBP15K. and one GPU might not be enough. Consequently, I tried to use torch.nn.DataParallel to run it on multiple GPUs, while it also failed to work. I wonder how you altered the code to make it work on DWY100K? (P.S. I have two Titan X GPUs)

Thank you very much for your time and I look forward to your reply.

**Comment by acharkq** [comment]
I run DWY100k on cpu. Lol.

**Comment by DexterZeng** [comment]
Cool.. I am doing the same thing right now, although it is really slow... 

Thanks!
