### ISSUE TITLE
Running the demo

### ISSUE THREAD

**Issue by fujiaz19** [thunlp/MuGNN#4]
Hi,

Thank you for sharing the code! I was following the instructions and trying to run the demo as the first step. Everything went well at the beginning and it successfully initialised a test folder in the log folder. 
![image](https://user-images.githubusercontent.com/43357141/90309559-f4fd0880-df2c-11ea-9548-5fde7383475b.png)

However, it then returned FileExistsError during the evaluation process.
![image](https://user-images.githubusercontent.com/43357141/90309489-61c3d300-df2c-11ea-9b90-25645024a331.png)

I was just wondering if I misunderstood anything. Can I please ask what might have gone wrong in this case and how to fix it? Thank you very much in advance and looking forward to your reply.

**Comment by acharkq** [comment]
The program will save a log every time when it is executed. The corresponding code is in L236 `def init_log' in config.py. 

I set the program to raise an error so that the logs from the previous experiments will not be overwritten.

You can remove L238-241 of config.py to stop raising this error.

**Comment by fujiaz19** [comment]
Hi, thank you so much for your quick reply! Yeah, that's also what I understood, but if I remove L238-241 I'll get
![image](https://user-images.githubusercontent.com/43357141/90324177-d2133880-dfae-11ea-92df-6e2b0408fdff.png)

Do you happen to know why it is like this? Many thanks!

**Comment by acharkq** [comment]
I think the error occurs because of window's different multiprocessing implementation. You can run the code on Linux and see if there is the same error.

**Comment by fujiaz19** [comment]
I see. Thank you for your reply! I will try to run in on Linux.

**Comment by fujiaz19** [comment]
Hi, sorry for the late update. The problem has been solved in the Linux environment. I'm very new to this so really appreciate your time and patience. Thank you again for the great work!
