### ISSUE TITLE
Error when no rules are found

### ISSUE THREAD

**Issue by fujiaz19** [thunlp/MuGNN#5]
Hi, I'm trying to run your code on a new dataset when after running the format_data.py, AMIE cannot find any rules for one of the graphs. Then, when I ran the train.py, it reported the following error: 
![Screenshot from 2020-09-28 01-15-22](https://user-images.githubusercontent.com/43357141/94368584-2e2db880-0128-11eb-9bca-6b8e850f4153.png)

I wonder if you could kindly let me know how I should deal with such situation so that I could run it successfully? Thank you so much in advance!

**Comment by acharkq** [comment]
This error occurs in printing.

You can try to comment line366-367 and line374-375 in the `cross_graph_completion.py' file.

Let me know if that works.

**Comment by fujiaz19** [comment]
Hi, thank you very much for your reply! The problem has been resolved now.

By the way, would you mind elaborating a bit more on if/how MuGNN uses attributes as I didn't find much information in the paper? Many thanks!!

**Comment by acharkq** [comment]
We didn't use any attributes in the MuGNN work. 

You can check out my latest work [Exploring and Evaluating Attributes, Values, and Structures for Entity Alignment](https://arxiv.org/abs/2010.03249) on EMNLP 2020 for utilizing various types of attribute triples within a GNN framework.

**Comment by fujiaz19** [comment]
I see, so can I ask what attr2id and ent2att files are for?

Thank you very much! I'll check that out!

**Comment by acharkq** [comment]
These two files are not used in the model.

**Comment by acharkq** [comment]
You are welcome!
