### ISSUE TITLE
Problem with the demo code

### ISSUE THREAD

**Issue by superhero5555** [thunlp/MuGNN#6]
Hello, when I was running the demonstration code example_train.py, the program did not respond after it started the evaluation, and the program seemed not to run，but it didn't report any errors. I would like to know what went wrong, thank you!
![QQ截图20201021195126](https://user-images.githubusercontent.com/73230704/96716046-1835af80-13d7-11eb-9f79-4063f803dda3.png)

**Comment by acharkq** [comment]
Are you running the program on cpu or gpu?

If you are running it on cpu, the evaluation will take very long.

**Comment by superhero5555** [comment]
Hello, the following errors occurred after the evaluation. May I ask what went wrong?Thank you.
<img width="505" alt="微信图片_20201025145447" src="https://user-images.githubusercontent.com/73230704/97100767-0ce1cd00-16d2-11eb-964f-d87f3df48b52.png">

**Comment by acharkq** [comment]
Have you removed the `config.py` file?

**Comment by superhero5555** [comment]
No 
![QQ截图20201025152759](https://user-images.githubusercontent.com/73230704/97101259-d6f31780-16d6-11eb-940e-c80b67d1f767.png)

**Comment by superhero5555** [comment]
Hello, the previous problem has been solved. Then I have a multithreading problem after removing an error message that already exists in the log\test file, I want to know how to solve it on Windows. thank you.
![QQ截图20201025194735](https://user-images.githubusercontent.com/73230704/97106162-f3a14680-16fa-11eb-9d09-758de3a406a2.png)

**Comment by acharkq** [comment]
I have updated the code to use GPU rather than multiprocessing for evaluation. 
This version should be ok on windows but will cost more GPU memory.

**Comment by acharkq** [comment]
Please let me know if there are further problems with running the demo code.

**Comment by superhero5555** [comment]
Thank you very much for your help. The demo code works without any problems.
